### ISSUE TITLE
Farsi Open Bible Stories

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#108]
Farsi Open Bible Stories

**Comment by JesniJ** [comment]
Completed testing and found some differences in the headings of stories in the content and the story headings listed on left side of the page.
story numbers are : 22, 18 , 29, 32, 43, 44, 48
Here attaching some of the screenshots.
![farsi_22_OBS](https://user-images.githubusercontent.com/102143707/177089787-e1928242-b061-426a-a515-7ee1880a7cb5.png)
![farsi_18_OBS](https://user-images.githubusercontent.com/102143707/177089809-5d7fef9c-3277-4015-ae11-897b4cca42cd.png)
![farsi_29_OBS](https://user-images.githubusercontent.com/102143707/177089840-3e309a8e-2ab8-40ab-a098-365ac68ba891.png)

![farsi_32_OBS](https://user-images.githubusercontent.com/102143707/177089862-252453e9-319a-450e-8242-95b8e1e2b581.png)

![farsi_44_OBS](https://user-images.githubusercontent.com/102143707/177089895-879b2660-965b-4399-9b10-c24e78cb2853.png)

As discussed moving this issue back to in-progress.

**Comment by AnuMonachan** [comment]
Took new md files from master version in door43 (https://door43.org/u/Door43-Catalog/fa_obs/master/01.html)
this fixed all the mentioned heading issues

**Comment by JesniJ** [comment]
Testing completed and all issues mentioned in headings are fixed. As discussed moving this issue to done.
