### ISSUE TITLE
Nepali Open Bible Stories

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#110]
Nepali Open Bible Stories

**Comment by AnuMonachan** [comment]
Fixed all the issues 
Took files from https://door43.org/u/Door43-Catalog/ne_obs/v8.1/

**Comment by LijuJacob08** [comment]
had tested the nepali OBS did'nt find any issue and above mentioned issues are fixed attaching the screenshot for the same.

![image](https://user-images.githubusercontent.com/93033055/177981630-dbe85830-b30e-40a2-8343-de888499c89c.png)

![image](https://user-images.githubusercontent.com/93033055/177981357-bb945ea0-4107-4552-a04f-d0978e20f105.png)
