### ISSUE TITLE
Varli Davri Bible (5 Books)

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#127]
NT Books - Mrk, Gal, Eph, Php & Col

**Comment by selvabenz** [comment]
- [ ] Starts with single quote symbol ends with double quotes is it ok?


![Image](https://user-images.githubusercontent.com/121541505/224242115-4d4b6f4f-55f1-488f-aab4-2e594971c37f.png)

- [ ]  Verse number 2 missing


![Image](https://user-images.githubusercontent.com/121541505/224242236-46c5599c-2a22-4ecc-a417-fc0945ac0683.png)

**Comment by AnnCherianA** [comment]
@selvabenz thank you for testing the content.
Could you also check whether the UI features are working -highlights, bookmarks etc

**Comment by selvabenz** [comment]
> @selvabenz thank you for testing the content. Could you also check whether the UI features are working -highlights, bookmarks etc

It is working as expected.

**Comment by AnnCherianA** [comment]
@selvabenz please mention the result of UI testing here and move this issue also accordingly

**Comment by selvabenz** [comment]
It is working as expected.

**Comment by selvabenz** [comment]
> @selvabenz please mention what are the basic features you tested. Moving back to QA for updating

UI features - highlights, bookmarks, notes, dictionary, commentary, info-graphic, audio and video are tested and working expected.
