### ISSUE TITLE
Koli-Kachhi Davri Bible (5 Books)

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#129]
NT Books - Mrk, Gal, Eph, Php & Col

**Comment by selvabenz** [comment]
- [ ] Combined Bible verses are showing different symbols


![Image](https://user-images.githubusercontent.com/121541505/224241376-ac92141a-912a-49d0-b802-5074bd6085bd.png)

- [ ] Bracket is missing 


![Image](https://user-images.githubusercontent.com/121541505/224241583-2f597864-613d-414e-8d0e-308cf3f27ab2.png)

- [ ] Is this an extra word? if so then there is a space missing


![Image](https://user-images.githubusercontent.com/121541505/224241829-e7574025-6387-4e9f-a7a4-281844d96bb5.png)

**Comment by selvabenz** [comment]
- [ ]  Is there any way to get back the deleted notes?

Basic UI is working as expected.

**Comment by AnnCherianA** [comment]
@selvabenz  please mention what are the basic features you tested. Moving back to QA for updating

**Comment by selvabenz** [comment]
> @selvabenz please mention what are the basic features you tested. Moving back to QA for updating

UI features - highlights, bookmarks, notes, dictionary, commentary, info-graphic, audio and video are tested and working expected.
