### ISSUE TITLE
Kukna OT Books (4 Books)

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#130]
OT 4 Books - Psa, Pro, Ecc & Sng

**Comment by selvabenz** [comment]
- [ ] Formatting 

> Default font size is too small to read if the font and the size is mimicked just like Gujarati it will be good.

> left align format will reduce the busyness in the text


![Image](https://user-images.githubusercontent.com/121541505/224238317-43146974-5184-43a8-ba91-330bb7b264aa.png)
![Image](https://user-images.githubusercontent.com/121541505/224238318-889c0c45-69c3-4e0f-8c5a-1763155ca285.png)
![Image](https://user-images.githubusercontent.com/121541505/224238319-5d63b4cf-09b9-4a7a-b6ac-2ce07ddc62a1.png)


- [ ] Chapter number is missing

![Image](https://user-images.githubusercontent.com/121541505/224238481-f4866635-6512-418c-a7c1-d27654c8b3a2.png)

- [ ] Current chapter number is not showing as default when we click the chapter navigation

![Image](https://user-images.githubusercontent.com/121541505/224238595-e51e98bd-640e-4e97-895e-529706f2de10.png)

- [ ] Different language name

![Image](https://user-images.githubusercontent.com/121541505/224238879-8e31276f-9405-4726-9bb6-8b34e8316454.png)


- [ ] Non-sync - when we change the language, it is not syncing as it should be in the parallel view

![Image](https://user-images.githubusercontent.com/121541505/224239026-7862bd1b-cb90-49da-9f80-a2d17d8c06eb.png)

**Comment by selvabenz** [comment]
Basic UI features are working as expected.

**Comment by AnnCherianA** [comment]
@selvabenz please mention what are the basic features you tested. Moving back to QA for updating
