### ISSUE TITLE
ISL Videos - Genesis & Luke

### ISSUE THREAD

**Issue by samuelanthrayose** [Bridgeconn/vachancontentrepository#132]

**Comment by JesniJ** [comment]
Tested stagging link , noted that data is not deployed here https://vachandev.netlify.app/
Thus moving this issue back to in-progress.

**Comment by samuelanthrayose** [comment]
It's on staging now. You may proceed

**Comment by JesniJ** [comment]
Testing done and found that alert meaasge need to change :
![isl_gen](https://user-images.githubusercontent.com/102143707/229125319-327172be-a24e-4ee7-bed4-eecfa0fddafd.png)
2. In the following references there exists background sound in the ISL videos
luke 3rd chapter 9:00 to 9:35
luke 4th chapter  9:00 to 10:14
luke 9th chapter , 19:00 to 20:26

Thus moving this issue back to in-progress

**Comment by AnuMonachan** [comment]
Have changed the message on staging, you can check

**Comment by JesniJ** [comment]
In the following references there exists background sound in the ISL videos
luke 3rd chapter 9:00 to 9:35
luke 4th chapter 9:00 to 10:14
luke 9th chapter , 19:00 to 20:26 
Thus am moving this issue back to in-progress , developers can move this issue to QA language as this has content issue.
For UI Anu has created another issue https://github.com/Bridgeconn/VachanOnline-v2/issues/288

**Comment by AnuMonachan** [comment]
Hi, this is just the first draft of the ISL videos, we can ignore check background noises and other minor issues in these videos

**Comment by JesniJ** [comment]
Here am adding screen recording for the references which have background noises. 

https://user-images.githubusercontent.com/102143707/233974174-2b509adf-6680-4496-b911-701f6c66549c.mp4

**Comment by samuelanthrayose** [comment]
Hi @JesniJ We are not to check the quality of the videos at this stage. These videos are just the initial draft of the first recording for ISL Bible. The need now is to share the ISL Bible to the community at the earliest. Let's move this issue to Done. The background noise issue will be notified to the ISL team, which will be taken up in their feedback when they do the next recording of these books.

**Comment by AnnCherianA** [comment]
@JesniJ as informed by Samuel, since the quality of sign video is not of importance at this point, please proceed in closing the issue

**Comment by JesniJ** [comment]
As discussed qa is ignoring minor issues in the videos and moving this issue to done .
