### ISSUE TITLE
Update infographics image filenames for all 11 languages

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#152]
Update infographics image filenames - remove spaces and hyphens from infographics image file names and replace them with an underscore

**Comment by AnuMonachan** [comment]
Removed all extra characters and replaced them with an underscore, removed old infographics data from staging and uploaded new files.

Infographics tested by QA:- 

- [ ] Bengali
- [ ] English
- [ ] Gujarati
- [ ] Hindi
- [ ] Kannada
- [ ] Malayalam
- [ ] Marathi
- [ ] Oriya
- [ ] Punjabi
- [ ] Tamil
- [ ] Telugu


You can tick the language box if all images are present, if not please mention it in the comments.

**Comment by AnnCherianA** [comment]
@selvabenz please test this issue and share your feedback

**Comment by selvabenz** [comment]
### **Please check the spelling**
![Spelling mistake-EZK-TAM](https://user-images.githubusercontent.com/121541505/231104712-414d042f-75a2-4406-8ad5-2ae2faabc3c1.png)

![Spelling mistake-DAN-TAM](https://user-images.githubusercontent.com/121541505/231104736-220c090a-5788-4df6-885e-ec84c0b69967.png)

![Spelling mistake-MRK-TAM](https://user-images.githubusercontent.com/121541505/231104734-4283e2f9-96b5-4c23-bf2f-c374e8ec6a31.png)

### **Infographic in English language there are no previews available in the mentioned images - but the main images can be viewed after the click.**

![No preview image-REV-ENG](https://user-images.githubusercontent.com/121541505/231104720-a110b3df-e3aa-4a58-b995-725c27e63adf.png)

![No preview image-HEB-ENG](https://user-images.githubusercontent.com/121541505/231104724-739c832b-52f9-4b4b-aada-53db90945bbc.png)

![No preview image-ROM-ENG](https://user-images.githubusercontent.com/121541505/231104725-07480cc5-fa18-40d7-a386-86c3f70a676b.png)

![No preview image-EXO-ENG](https://user-images.githubusercontent.com/121541505/231104742-3a248269-c0d0-4bd8-b919-b83523304717.png)

**Comment by selvabenz** [comment]
There are some of the content and images needs attention therefore moved the issue to in-progress.

**Comment by AnnCherianA** [comment]
@selvabenz please verify the fix.

**Comment by selvabenz** [comment]
- Mentioned preview issues were fixed and moving the issue to done.
**- Note: In Tamil the spelling mistakes are not fixed.**

**Comment by AnnCherianA** [comment]
@selvabenz  please raise a separate issue for the spelling issues noted here and assign to Anu. @AnuMonachan please update your comments as discusssed and move it to the appropriate phase.

**Comment by selvabenz** [comment]
A new issue has been initiated for spelling check. Hence moving the issue to done.
https://github.com/Bridgeconn/vachancontentrepository/issues/154
