### ISSUE TITLE
OBT Audio Bible Bommala

### ISSUE THREAD

**Issue by svishnu06** [Bridgeconn/vachancontentrepository#159]
[Bommala OBT](https://bridgeconn-my.sharepoint.com/personal/abhishek_lama_bridgeconn_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fabhishek%5Flama%5Fbridgeconn%5Fcom%2FDocuments%2FOBT%2FOBT%20Bommala&ga=1)

**Comment by JesniJ** [comment]
Testing completed and verified that OBT audio bible in Bommala is added for the books 1Th, 2Th, Mark, Luke . Therefore moving this issue to Done.
