### ISSUE TITLE
OBT Audio Bible Kongaru

### ISSUE THREAD

**Issue by svishnu06** [Bridgeconn/vachancontentrepository#161]
[Kongaru OBT](https://bridgeconn-my.sharepoint.com/personal/abhishek_lama_bridgeconn_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fabhishek%5Flama%5Fbridgeconn%5Fcom%2FDocuments%2FOBT&ga=1)

**Comment by AnnCherianA** [comment]
@VineethaVi please check the content and udpate

**Comment by VineethaVi** [comment]
Testing completed. Verified that OBT audio bible in Kongaru language is added for the books 1 Thessalonians,2 Thessalonians, Mark ,Luke. Moving to Done.
