### ISSUE TITLE
To make usfm file for ERV revision 2014

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/vachancontentrepository#172]
To convert pdf file of ERV revision 2014 to usfm format.

**Comment by AnnCherianA** [comment]
Attaching the email conversation 
[Email - ERV 2014 pdf to usfm.pdf](https://github.com/Bridgeconn/vachancontentrepository/files/11786265/Email.-.ERV.2014.pdf.to.usfm.pdf)

**Comment by svishnu06** [comment]
@AnnCherianA  Could you please send me the pdf file  .

**Comment by JesniJ** [comment]
[ENGERV.pdf](https://github.com/Bridgeconn/vachancontentrepository/files/11795908/ENGERV.pdf)

Here am attaching pdf file of ENG ERV-2014

**Comment by samuelanthrayose** [comment]
This was tried out with a couple of libraries, and working on this seems impossible, as the PDF is not in a format, where text can be extracted easily. It would require manual copying and verification of each verse. So moving this ticket to closed for now
