### ISSUE TITLE
Some ISL videos not loading in VO- have been removed

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/vachancontentrepository#173]
In Vachan Online ,  some ISL videos are not loading . The message ' The video has been removed by the uploader '  is shown

Steps:
Open ESV -Genesis 1 in the reading pane. 
Select ISLV on the top bar

The first video of Genesis one shows the  message ' Video Unavailable . The video has been removed by the uploader '

![image](https://github.com/Bridgeconn/vachancontentrepository/assets/74647279/fc170b49-75d3-45a6-bd6b-af4a96458ac5)

**Comment by JesniJ** [comment]
Also noticed that videos has removed from the book luke chapters  3,4,7,9,11 and 12

**Comment by AnnCherianA** [comment]
@VineethaVi  please mention the list of videos are private

**Comment by VineethaVi** [comment]
In the book Luke chapters 11 and 12 are private

**Comment by Leni-Easo** [comment]
json file uploaded #177

**Comment by Leni-Easo** [comment]
Added books and chapters are:
1. Gen 1-50
2. Jos 1-10
3. Rut 1-4
4. Mat 1-28
5. Mrk 1-16
6. Luk 1-24
7. Tit 1-3
8. Acts 1-14
9. 1 Th 1-5
10. 2 Th 1-3
11. Jud 1

**Comment by VineethaVi** [comment]
Test Result 

 selected Genesis 1 in English ESV language
opened the reading page
selected ISL Video  from the top bar
It showing the ISL video of Introduction of the book Genesis and the chapter 1.
It is working fine.  Testing done on chrome.

![ISLVIDEOO](https://github.com/Bridgeconn/vachancontentrepository/assets/132653333/b0a92390-78ae-46a1-a8e6-2219360fd266)



Tested and verified that the listed ISL Videos are added and It is working fine. Testing done on chrome.

Introduction of the book Genesis and chapters 1 to 50 
 Introduction of the book Joshua and chapters 1 to 10 
 Introduction of the book Ruth and chapters 1 to 4 
 Introduction of the book Matthew and chapters 1 to 28 
Introduction of the book Mark and chapters 1 to 16 
 Introduction of the book Luke and chapters 1 to 24 
Introduction of the book Titus and chapters 1 to 3 
Introduction of the book Acts and chapters 1 to 14 
Introduction of the book 1 Thessalonians and chapters 1 to 5 
 Introduction of the book  2Thessalonians and chapters 1 to 3
 Introduction of the book Jude and chapter 1 .

**Comment by VineethaVi** [comment]
Moving to Done
