### ISSUE TITLE
Hindi IRV Audio Bibles Full Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#19]
Added Hindi IRV Audio Bibles for OT & NT.

**Comment by AnnCherianA** [comment]
Testing is in progress by Savitha

**Comment by savithasusannamark** [comment]
Checked full bible but 2John is not playing

**Comment by AnuMonachan** [comment]
- [x] Hindi IRV - 2 John - Audio file does not play - Issue has been resolved by Samuel.

**Comment by savithasusannamark** [comment]
2John audio is playing now
