### ISSUE TITLE
Haryanvi HB Audio Bibles NT

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#21]
Added Haryanvi HB Audio Bibles NT.

**Comment by AnnCherianA** [comment]
Testing is in progress by Savitha

**Comment by savithasusannamark** [comment]
@AnnCherianA  hello Ann sharing the  haryanvi audio test link here: 
https://bridgeconn-my.sharepoint.com/:x:/r/personal/savitha_mark_bridgeconn_com/_layouts/15/Doc.aspx?sourcedoc=%7B0F1701BF-AAB7-417D-A35C-20C2C0D89E82%7D&file=Book%205.xlsx&wdOrigin=OFFICECOM-WEB.START.REC&ct=1620123234670&action=default&mobileredirect=true

**Comment by AnuMonachan** [comment]
- [x] Haryanvi - Philippians -Audio file does not play .

Issue has been resolved by Samuel.

**Comment by savithasusannamark** [comment]
Haryanvi - Philippians is playing now
