### ISSUE TITLE
Bilaspuri NT Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#22]
- [x] Parse Bilaspuri USFM files.
- [x] Upload to staging

**Comment by AnuMonachan** [comment]
- [ ]Test Bilaspuri bible for any issues.

**Comment by savithasusannamark** [comment]
Checked audio bible for Bilaspuri_NT. mark, Philippians and 1timothy are not playing, and test report is here:
 
https://bridgeconn-my.sharepoint.com/:x:/r/personal/savitha_mark_bridgeconn_com/_layouts/15/Doc.aspx?sourcedoc=%7B0F1701BF-AAB7-417D-A35C-20C2C0D89E82%7D&file=Audio_test.xlsx&wdOrigin=OFFICECOM-WEB.START.REC&ct=1620718941164&action=default&mobileredirect=true

**Comment by savithasusannamark** [comment]
Checked the Bilaspuri bible and all feature is working fine.

**Comment by AnnCherianA** [comment]
The landing page displays Bilaspuri Bible as Kfs-BSV which is not easy for the user to understand. It will be easier for the user to understand if it is denoted as BIL.

**Comment by AnnCherianA** [comment]
QA Review comments  based on the document uploaded for Bilaspuri NT :   https://bridgeconn-my.sharepoint.com/:x:/r/personal/savitha_mark_bridgeconn_com/_layouts/15/Doc.aspx?sourcedoc=%7B86F99FC1-3C5A-4BC2-B379-4DDCBFDA7D37%7D&file=Bible_feature.xlsx&wdOrigin=OFFICECOM-WEB.START.REC&ct=1621508532960&action=default&mobileredirect=true&cid=4d6b3c45-cceb-49cc-8dcc-ae1f9ac15899
The test report has covered  all the features for Bilaspuri NT  . 
Please make the following changes . 
- Commentary, Dictionary can be removed 
-  The highlight for audio not available can be removed as it is not an issue. 

-Previous and Next chapters need not be mentioned as a features . Please upload the updated report.  For the teams channel, please share the updated report in the path QA -Vachan Online ->1.2.0

**Comment by savithasusannamark** [comment]
Uploaded the updated report for Bilaspuri audio bible is here: https://teams.microsoft.com/_#/files/VachanOnline%20-%20VachanGo?threadId=19%3Ada158eb0344e43bbafde58bf14f8df44%40thread.tacv2&ctx=channel&context=1.2.0&rootfolder=%252Fsites%252FDevTeam-VachanUI-VachanGo%252FShared%2520Documents%252FVachan%2520UI%2520-%2520VachanGo%252FQA%252FVachan%2520Online%252F1.2.0
