### ISSUE TITLE
Repetition of ‘had’ in Mark 5:15,25 - English ESV

### ISSUE THREAD

**Issue by Leni-Easo** [Bridgeconn/vachancontentrepository#226]
In the English ESV, Mark chapter 5, verses 15 and 25 have a repetition of 'had had'.

**Comment by Leni-Easo** [comment]
Corrected 42MRKGSB.SFM file of the English ESV
The correction is 'had had'  with  'had'  in the Eng-ESV Bible.
[PR Link](https://github.com/Bridgeconn/Vachan-Copyright-Content/pull/33)

**Comment by Leni-Easo** [comment]
Based on Joel Mathew's comment at https://github.com/Bridgeconn/Vachan-Copyright-Content/pull/33#issuecomment-1857457605 since this isn't considered an error, closing out this issue as resolved.

**Comment by VineethaVi** [comment]
Issue is reopened for adding this comment .By mistake I asked Lenitta move the issue to QA . This issue is not supposed  move to QA as it doesn't exist.  

So, closing this issue.
