### ISSUE TITLE
Bilaspuri Audio Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#23]
- [x] Add Bilaspuri Audio Bible to staging

**Comment by AnuMonachan** [comment]
- [ ] Check for any issues in Bilaspuri Audio Bibles.

**Comment by savithasusannamark** [comment]
Checked audio bible for Bilaspuri_NT. mark, Philippians and 1timothy are not playing, and test report is here:

https://bridgeconn-my.sharepoint.com/:x:/r/personal/savitha_mark_bridgeconn_com/_layouts/15/Doc.aspx?sourcedoc=%7B0F1701BF-AAB7-417D-A35C-20C2C0D89E82%7D&file=Audio_test.xlsx&wdOrigin=OFFICECOM-WEB.START.REC&ct=1620718941164&action=default&mobileredirect=true

**Comment by savithasusannamark** [comment]
Bilaspuri audio bible is checked and is working fine.  test report is here: https://bridgeconn-my.sharepoint.com/:x:/r/personal/savitha_mark_bridgeconn_com/_layouts/15/Doc.aspx?sourcedoc=%7B0F1701BF-AAB7-417D-A35C-20C2C0D89E82%7D&file=Audio_test.xlsx&wdOrigin=OFFICECOM-WEB.START.REC&ct=1620902807972&action=default&mobileredirect=true
;
