### ISSUE TITLE
Dogri NT Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#26]
- [x] Parse NT Bible USFM Files (fix issues)

- [x] Upload to Staging

- [x] Test for issues

- [x] Upload to Production

**Comment by savithasusannamark** [comment]
Tested Dogri NT Bible all features are working fine. test report is here https://teams.microsoft.com/_#/files/VachanOnline%20-%20VachanGo?threadId=19%3Ada158eb0344e43bbafde58bf14f8df44%40thread.tacv2&ctx=channel&context=1.2.0&rootfolder=%252Fsites%252FDevTeam-VachanUI-VachanGo%252FShared%2520Documents%252FVachan%2520UI%2520-%2520VachanGo%252FQA%252FVachan%2520Online%252F1.2.0

**Comment by AnnCherianA** [comment]
@savithasusannamark  please move this to Done
