### ISSUE TITLE
Oriya IRV Audio Bible

### ISSUE THREAD

**Issue by Anu-44** [Bridgeconn/vachancontentrepository#29]
- [x] Check if all Audio Bible files are available.

- [x] Upload to Staging.

- [ ] Test for issues.

- [ ] Upload to Production.

**Comment by AnnCherianA** [comment]
@savithasusannamark please proceed in testing the Oriya audio  Bible.

**Comment by savithasusannamark** [comment]
Checked Oriya IRV Audio bible and is working fine: please find the report here: https://teams.microsoft.com/_#/files/VachanOnline%20-%20VachanGo?threadId=19%3Ada158eb0344e43bbafde58bf14f8df44%40thread.tacv2&ctx=channel&context=1.2.0&rootfolder=%252Fsites%252FDevTeam-VachanUI-VachanGo%252FShared%2520Documents%252FVachan%2520UI%2520-%2520VachanGo%252FQA%252FVachan%2520Online%252F1.2.0
