### ISSUE TITLE
English BBE

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#35]
- [x] Parse Bible USFM Files (fix issues)

- [x] Upload to Staging

- [x] Test for issues

- [ ] Upload to Production

**Comment by LijuJacob08** [comment]
Observations:-

- special char like for eg. Inn BBE version Jermiah 40:3  *** was there in the original content.

screenshots
-staging
![Screenshot from 2021-12-15 10-10-15](https://user-images.githubusercontent.com/93033055/146124421-b258d64a-7c1d-40bf-8b68-e40beae510ec.png)

-ebible
![Screenshot from 2021-12-15 10-13-42](https://user-images.githubusercontent.com/93033055/146124677-40c35dcb-714d-48e0-a6a1-cb2769c19b34.png)

**Comment by AnuMonachan** [comment]
This is fine as the data is similar in the original site also.

**Comment by LijuJacob08** [comment]
ok.moving to done.
