### ISSUE TITLE
English WEB Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#36]
- [x] Parse Bible USFM Files (fix issues)

- [x] Upload to Staging

- [ ] Test for issues

- [ ] Upload to Production

**Comment by LijuJacob08** [comment]
Observations:
-There are possibilities like there might be opening qoutes but closing qoutes(Which is also there in the original content)
(eg Leviticus13)
-Certain places  qoutes like “ ‘ “ for us(Vachan) it’s showing like “‘“(eg jermiah 19 :7).

screenshots
**staging**
![Screenshot from 2021-12-15 10-29-00](https://user-images.githubusercontent.com/93033055/146126206-bf3a101e-34ad-40c5-bb1a-e961d0670b4f.png)

**ebible**
![Screenshot from 2021-12-15 10-28-04](https://user-images.githubusercontent.com/93033055/146126165-7bebe443-715c-4ff1-83a6-361be0cc7843.png)
 
are we good with the changes we see ?

**Comment by AnuMonachan** [comment]
This is fine, issue is due to font difference.

**Comment by LijuJacob08** [comment]
moving to done.
