### ISSUE TITLE
English UDB Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#37]
- [x] Parse Bible USFM Files (fix issues)

- [x] Upload to Staging

- [x] Test for issues

- [ ] Upload to Production

**Comment by LijuJacob08** [comment]
Observations:-
-Certain places qoutes like '"(small space between first and second) in vachan it’s showing like. '" eg(Leviticus 17)
staging
![Screenshot from 2021-12-15 12-12-13](https://user-images.githubusercontent.com/93033055/146136572-8e6cff22-c4f9-4c0a-b408-649b0d5cb172.png)

unfloding
![Screenshot from 2021-12-15 12-10-42](https://user-images.githubusercontent.com/93033055/146136444-249b6c04-ceb8-42b4-8ca2-e1d97d5bbc12.png)

**Comment by AnuMonachan** [comment]
This is fine, issue is due to font difference.

**Comment by LijuJacob08** [comment]
moving to done
