### ISSUE TITLE
English ULB Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#38]
- [x] Parse Bible USFM Files (fix issues)

- [x] Upload to Staging

- [x] Test for issues

- [ ] Upload to Production

**Comment by LijuJacob08** [comment]
Observations:

1.  certain words appended at the end like BETH, DALETH ,HE VAV etc checked the same in the unfolding words ULB version there it looks like heading for the successive verses.

2. other than this first heading 'ALEPH' is missing


attaching screenshots for the both-
-staging
![Screenshot from 2021-12-15 10-00-56](https://user-images.githubusercontent.com/93033055/146123613-eaa5ab41-bae0-4483-bbc9-bd33fc093b4b.png)

- unfolding ULB
![Screenshot from 2021-12-15 10-04-15](https://user-images.githubusercontent.com/93033055/146123871-839c4f4f-9e49-4bc3-a477-1b83972450d4.png)

ALEPH  is missing in the staging one.
![ULB Beth](https://user-images.githubusercontent.com/93033055/146123457-ca006a83-9e31-4056-bd59-02d3aaa53438.png)

**Comment by AnuMonachan** [comment]
Hi will be moving every content with data issues after testing to content issue pipeline, will assign it back to QA after fixing the issues.

**Comment by AnuMonachan** [comment]
Content is fine, need to update usfm-grammar to fix this, as discussed in 21 Dec meeting, we can upload to production.

**Comment by LijuJacob08** [comment]
moving to done
