### ISSUE TITLE
ESV Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#6]
- [x] Test new usfm-grammar in sandbox, Upload ESV bibles to sandbox
- [x] Send PR to vachan-engine v1 for new usfm-grammar compatible code
- [x] Send PR to vachan-admin for new usfm-grammar 
- [x] update VO to read new json structure 
- [ ] Update VachanApp to read new json structure

**Comment by AnnCherianA** [comment]
QA Review comments based on the document uploaded for ESV Bible  : https://bridgeconn-my.sharepoint.com/:x:/r/personal/savitha_mark_bridgeconn_com/_layouts/15/Doc.aspx?sourcedoc=%7B86F99FC1-3C5A-4BC2-B379-4DDCBFDA7D37%7D&file=Bible_feature.xlsx&wdOrigin=OFFICECOM-WEB.START.REC&ct=1621508532960&action=default&mobileredirect=true&cid=4d6b3c45-cceb-49cc-8dcc-ae1f9ac15899
The test report has covered all the features for ESV Bible 
Please make the following changes .
Commentary, Dictionary can be removed as these are not specific to the ESV Bible .
The highlight for audio not available can be removed as it is not an issue.
-Previous and Next chapters need not be mentioned as a features . Please upload the updated report. For the teams channel, please share the updated report in the path QA -Vachan Online ->1.2.0

**Comment by savithasusannamark** [comment]
updated test report is here: https://teams.microsoft.com/_#/files/VachanOnline%20-%20VachanGo?threadId=19%3Ada158eb0344e43bbafde58bf14f8df44%40thread.tacv2&ctx=channel&context=1.2.0&rootfolder=%252Fsites%252FDevTeam-VachanUI-VachanGo%252FShared%2520Documents%252FVachan%2520UI%2520-%2520VachanGo%252FQA%252FVachan%2520Online%252F1.2.0
