### ISSUE TITLE
ESV Audio Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#67]
- [x] Upload to Staging
- [x] Test for issues 
- [x] Fix issues (if found)
- [x] Upload to Production

**Comment by AnnCherianA** [comment]
@LijuJacob08 please test the ESV Audio bible and update the result

**Comment by LijuJacob08** [comment]
Hi, 
had tested the ESV Audio bible , results were as expected . moving it done.
Thanks
