### ISSUE TITLE
BBC Commentaries (English, Gujarati & Marathi)

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#7]
- [x] Add tables & image tags in all BBC Commentaries.
- [x] Add BBC Commentaries & images to github.
- [x] Put metadata- imageBaseURL in commentary
- [ ] Upload to staging.
- [ ] Check English, Gujarati & Marathi BBC Commentaries for missing Content.
- [ ] Check if images are in right location in all Commentaries.

- This [bbc_images.docx](https://github.com/Bridgeconn/vachancontentrepository/files/6350228/bbc_images.docx)  file has all the image references in english bbc commentary in bcv format alongwith the image name.

**Comment by AnnCherianA** [comment]
Test Report for Commentary image location 
The test report for the images loaded for English, Gujarati and Marathi commentaries  have been shared to Anu Monachan
Pending : Testing images which are included in the Introduction section of the images.
https://bridgeconn-my.sharepoint.com/:x:/p/ann_cherian/Ec82qoLTBVVAozdGurrY4_gBpf7W1gZ_DxRFQPWkoT0jXQ?e=ifIGg8
Some of the common issues noted were


	
The image located at a particular section of verses for English or Marathi  may be located at a different section for Gujarati
	The image may be available but not loading 
	The image expected to be located at particular verse locations may not be available.
