### ISSUE TITLE
Gujarati TBP Videos

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#71]

**Comment by AnnCherianA** [comment]
@LijuJacob08  please test the TBP videos and share the update

**Comment by LijuJacob08** [comment]
Videos are available and playing as expected. 
but one thing which I noticed Gujarati -Jude video that in the intro it's showing bible project marathi, are we good we this ?

![image](https://user-images.githubusercontent.com/93033055/154969471-f0ddc48b-688f-4e48-bda2-83c0eb46a36e.png)

**Comment by LijuJacob08** [comment]
moving to done.

**Comment by AnuMonachan** [comment]
Got new link from Bible Project, will update the link and assign it to QA

**Comment by LijuJacob08** [comment]
attaching the screenshot
![image](https://user-images.githubusercontent.com/93033055/155987458-aa119d37-86ef-468d-bb69-c2e4a0359d30.png)

moving to done

**Comment by LijuJacob08** [comment]
checked in production , moving to done.
