### ISSUE TITLE
Marathi TBP Videos

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#72]

**Comment by AnnCherianA** [comment]
@LijuJacob08  please test the TBP videos and share the update

**Comment by LijuJacob08** [comment]
Videos are available and playing as expected. 
but notices one odd thing  - for 2Corinthians video the thumbnail is in Kannada.
are we good with this?
![image](https://user-images.githubusercontent.com/93033055/154968158-8720e203-4e01-409f-9bc0-ae4479d0d3c3.png)

**Comment by AnuMonachan** [comment]
All the content related issues will be fixed by BibleProject.

**Comment by LijuJacob08** [comment]
moving to done.

**Comment by AnuMonachan** [comment]
this has been fixed by bibleproject team.

**Comment by LijuJacob08** [comment]
thumbnail has been fixed
attaching the screenshot 
![image](https://user-images.githubusercontent.com/93033055/155988570-f90fa5d1-6bdf-4f46-941e-54dbdd409e81.png)

**Comment by LijuJacob08** [comment]
checked in production, moving to closed.
