### ISSUE TITLE
Bengali TBP Videos

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#76]

**Comment by LijuJacob08** [comment]
Hi Anu,
all the videos are available and loading as expected, but noticed that for Dueteronomy video description there is D30 mentioned at the end of the the description section, are we good with this?
![image](https://user-images.githubusercontent.com/93033055/154964612-e53efa1a-22da-4308-b44a-a6a5b1b3b3c7.png)

**Comment by AnuMonachan** [comment]
All the content related issues will be fixed by BibleProject, For this we can remove the cell no. accidentally mentioned in the description

**Comment by LijuJacob08** [comment]
moving to done.

**Comment by AnuMonachan** [comment]
this has been fixed by bibleproject team.

**Comment by LijuJacob08** [comment]
it is fixed now
![image](https://user-images.githubusercontent.com/93033055/155989729-d918fafc-9676-43cd-bedc-e9f19dd087de.png)

**Comment by LijuJacob08** [comment]
checked in production, moving to closed
