### ISSUE TITLE
Malayalam TBP Videos

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#77]
Hi Anu, 
Following are the things which i noticed,
1. No description -Exodus 1-18 , 1-2 Sam,1-2 Kings
![image](https://user-images.githubusercontent.com/93033055/154988628-7c174315-22d6-4c61-9975-e88a6ae342cb.png)

2. NT books have more videos than the one mentioned in the CSV file.
eg  the video in mark was not mentioned in csv file.
![image](https://user-images.githubusercontent.com/93033055/154988357-ba50733e-cb0b-4851-8d85-876a8dd352b2.png)

3. the video panel does'nt seem to be able to contain videos the videos on the right had passed the right boundary of panel and cant see the vertical scroll bar for the panel as well.
![image](https://user-images.githubusercontent.com/93033055/154987502-abfa4a2d-5c88-45b6-a638-6798fcb3e6b0.png)

**Comment by LijuJacob08** [comment]
Hi Anu, 
Following are the things which i noticed,
-No description -Exodus 1-18 , 1-2 Sam,1-2 Kings
![image](https://user-images.githubusercontent.com/93033055/154988628-7c174315-22d6-4c61-9975-e88a6ae342cb.png)

-NT books have more videos than the one mentioned in the CSV file.
eg  the video in mark was not mentioned in csv file.
![image](https://user-images.githubusercontent.com/93033055/154988357-ba50733e-cb0b-4851-8d85-876a8dd352b2.png)


-the video panel does'nt seem to be able to contain videos the videos on the right had passed the right boundary of panel and cant see the vertical scroll bar for the panel as well.
![image](https://user-images.githubusercontent.com/93033055/154987502-abfa4a2d-5c88-45b6-a638-6798fcb3e6b0.png)

**Comment by AnuMonachan** [comment]
The extra videos are from a different playlist added before this, the panel issue is a code problem will be fixing that

**Comment by LijuJacob08** [comment]
ok moving to done

**Comment by AnuMonachan** [comment]
Moving to in progress, will be fixing the layout problem and then will assign to QA. [VO issue #162](https://github.com/Bridgeconn/VachanOnline-v2/issues/162)

**Comment by AnuMonachan** [comment]
Layout issue has been fixed, [VO issue #162](https://github.com/Bridgeconn/VachanOnline-v2/issues/162)

**Comment by LijuJacob08** [comment]
was tested in [#162](https://github.com/Bridgeconn/VachanOnline-v2/issues/162). hence moving to done.
