### ISSUE TITLE
Bengali Infographics

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#78]
One file is missing from bengali infographics - Jonah_Overview

**Comment by LijuJacob08** [comment]
Hi Anu,
Had completed my testing as per the csv which was shared, did'nt see jonah overview  neither on the list images in the csv nor on the any other bible as well(guj, kan, mal, mar, ory, pan, tam, tel bibles)
thing which i found - all images are loading except the- one in book 48(Galatians) -named-"Promise Law Jesus".
![image](https://user-images.githubusercontent.com/93033055/154907189-5f4b0169-442f-458e-825e-99d839075f2e.png)

**Comment by LijuJacob08** [comment]
looks good to me.
![image](https://user-images.githubusercontent.com/93033055/154931680-fd8a66d0-53f5-4ef9-a8e9-26a306950e28.png)


moving to done.
