### ISSUE TITLE
Haryanvi NT Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#8]
Haryanvi NT HB Bible

**Comment by AnnCherianA** [comment]
@AnuMonachan Is Haryanvi NT Bible tested?

**Comment by AnuMonachan** [comment]
it was in staging for sometime, then we were told to upload in production also 
we are not sure if it is tested or not.
content checking was started a while we usually dont check the content we just check if usfm grammar is able to parse the files and then we upload it.
