### ISSUE TITLE
Kannada Infographics

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#81]

**Comment by LijuJacob08** [comment]
Hi Anu,
Had completed my testing( used the infographics.csv file for reference). 
thing which i found - all images are loading except the- one in book 48(Galatians) -named-"Promise Law Jesus".
![image](https://user-images.githubusercontent.com/93033055/154906353-01e2ff8b-c2eb-4cfd-b051-8d9c968fb2c0.png)

**Comment by LijuJacob08** [comment]
looks god to me.
![image](https://user-images.githubusercontent.com/93033055/154929318-9c925aad-18ec-4a35-af1a-deb16e8c4fbc.png)

moving to done.
