### ISSUE TITLE
Tamil infographics

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#85]
One infographic file missing - Paul's life & mission timeline

**Comment by LijuJacob08** [comment]
Hi Anu,
Had completed my testing( used the infographics.csv file for reference). 
thing which i found - all images are loading except the- one in book 48(Galatians) -named-"Promise Law Jesus".
![image](https://user-images.githubusercontent.com/93033055/154906353-01e2ff8b-c2eb-4cfd-b051-8d9c968fb2c0.png)

**Comment by LijuJacob08** [comment]
looks good to me.
![image](https://user-images.githubusercontent.com/93033055/154930205-fbe049b3-6619-4e34-9af6-cf96cddfa7a9.png)

 moving to done.
