### ISSUE TITLE
Marathi infographics

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#87]

**Comment by LijuJacob08** [comment]
Hi Anu,
Had completed my testing( used the infographics.csv file for reference). 
thing which i found - all images are loading except the- one in book 48(Galatians) -named-"Promise Law Jesus".
![image](https://user-images.githubusercontent.com/93033055/154906353-01e2ff8b-c2eb-4cfd-b051-8d9c968fb2c0.png)

**Comment by LijuJacob08** [comment]
looks good to me.
![image](https://user-images.githubusercontent.com/93033055/154929517-763151c5-5f38-4551-8c38-cff367e27e42.png)

moving to done.
