### ISSUE TITLE
ESV Study Notes

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#90]
- [x] Convert files to required format (Create script for conversion).
- [x] Upload to sandbox server and check.
- [x] Upload to staging and assign to QA.
- [x] Upload to production.

**Comment by LijuJacob08** [comment]
Hi Anu,
had confirmed that commentary is available and loading for the entire bible and apart from it had noticed following things, can you please confirm whether they are expected to be like this or not:
1. few places noticed that book name were missing before the chapter:verse. are these expected to be like this.?
eg

 ![image](https://user-images.githubusercontent.com/93033055/170559960-f1fadabf-a2b7-4090-9d09-5ff2a3f07da2.png)
attaching the list for the the same- [BookName_missing.txt](https://github.com/Bridgeconn/vachancontentrepository/files/8781551/BookName_missing.txt)


2. and at some places saw somethng like->  v.{number} and vv{num}. were these suppose to be the some hyperlink..?
eg
![image](https://user-images.githubusercontent.com/93033055/170559502-2a93321e-3433-41d6-9e2c-b754937f96b6.png)

**Comment by AnuMonachan** [comment]
Thank you liju, these are fine, the data in xml is like this, we are currently not providing any hyperlinks, the xml has those so there might be some in the content also

**Comment by LijuJacob08** [comment]
as per the discussion above moving it to done

**Comment by AnuMonachan** [comment]
You can move it to closed as well

**Comment by LijuJacob08** [comment]
closing this one.
