### ISSUE TITLE
Gujarati IRV Audio Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#93]

**Comment by AnuMonachan** [comment]
- [x] Upload to Staging
- [ ] Upload to Production

**Comment by AnnCherianA** [comment]
@JesniJ please test and share your feedback

**Comment by JesniJ** [comment]
Gujarati IRV audio files are working properly

**Comment by LijuJacob08** [comment]
As Jesni had completed the testing and no issues were found . hence moving the task to done.
