### ISSUE TITLE
Kannada IRV Audio Bible

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#94]

**Comment by AnuMonachan** [comment]
- [x] Upload to Staging
- [ ] Upload to Production

**Comment by AnnCherianA** [comment]
@LijuJacob08 please test and share your feedback

**Comment by LijuJacob08** [comment]
tested the Audio bible, verified that every chapter had an audio file as expected and no issues were found.hence moving this done.
